#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BanVeXe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_XEKHACH")]
	public partial class Data_BanVeXeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUYENDI(CHUYENDI instance);
    partial void UpdateCHUYENDI(CHUYENDI instance);
    partial void DeleteCHUYENDI(CHUYENDI instance);
    partial void InsertDIADIEMLENXE(DIADIEMLENXE instance);
    partial void UpdateDIADIEMLENXE(DIADIEMLENXE instance);
    partial void DeleteDIADIEMLENXE(DIADIEMLENXE instance);
    partial void InsertGHE(GHE instance);
    partial void UpdateGHE(GHE instance);
    partial void DeleteGHE(GHE instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLIENHE(LIENHE instance);
    partial void UpdateLIENHE(LIENHE instance);
    partial void DeleteLIENHE(LIENHE instance);
    partial void InsertLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void UpdateLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void DeleteLOAINGUOIDUNG(LOAINGUOIDUNG instance);
    partial void InsertLOAINHANVIEN(LOAINHANVIEN instance);
    partial void UpdateLOAINHANVIEN(LOAINHANVIEN instance);
    partial void DeleteLOAINHANVIEN(LOAINHANVIEN instance);
    partial void InsertLOAIXE(LOAIXE instance);
    partial void UpdateLOAIXE(LOAIXE instance);
    partial void DeleteLOAIXE(LOAIXE instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNOIDEN(NOIDEN instance);
    partial void UpdateNOIDEN(NOIDEN instance);
    partial void DeleteNOIDEN(NOIDEN instance);
    partial void InsertNOIDI(NOIDI instance);
    partial void UpdateNOIDI(NOIDI instance);
    partial void DeleteNOIDI(NOIDI instance);
    partial void InsertPHUXE(PHUXE instance);
    partial void UpdatePHUXE(PHUXE instance);
    partial void DeletePHUXE(PHUXE instance);
    partial void InsertTAIXE(TAIXE instance);
    partial void UpdateTAIXE(TAIXE instance);
    partial void DeleteTAIXE(TAIXE instance);
    partial void InsertTUYENDI(TUYENDI instance);
    partial void UpdateTUYENDI(TUYENDI instance);
    partial void DeleteTUYENDI(TUYENDI instance);
    partial void InsertVE(VE instance);
    partial void UpdateVE(VE instance);
    partial void DeleteVE(VE instance);
    partial void InsertXE(XE instance);
    partial void UpdateXE(XE instance);
    partial void DeleteXE(XE instance);
    #endregion
		
		public Data_BanVeXeDataContext() : 
				base(global::DAL_BanVeXe.Properties.Settings.Default.DB_XEKHACHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data_BanVeXeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_BanVeXeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_BanVeXeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_BanVeXeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUYENDI> CHUYENDIs
		{
			get
			{
				return this.GetTable<CHUYENDI>();
			}
		}
		
		public System.Data.Linq.Table<DIADIEMLENXE> DIADIEMLENXEs
		{
			get
			{
				return this.GetTable<DIADIEMLENXE>();
			}
		}
		
		public System.Data.Linq.Table<GHE> GHEs
		{
			get
			{
				return this.GetTable<GHE>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LIENHE> LIENHEs
		{
			get
			{
				return this.GetTable<LIENHE>();
			}
		}
		
		public System.Data.Linq.Table<LOAINGUOIDUNG> LOAINGUOIDUNGs
		{
			get
			{
				return this.GetTable<LOAINGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<LOAINHANVIEN> LOAINHANVIENs
		{
			get
			{
				return this.GetTable<LOAINHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<LOAIXE> LOAIXEs
		{
			get
			{
				return this.GetTable<LOAIXE>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NOIDEN> NOIDENs
		{
			get
			{
				return this.GetTable<NOIDEN>();
			}
		}
		
		public System.Data.Linq.Table<NOIDI> NOIDIs
		{
			get
			{
				return this.GetTable<NOIDI>();
			}
		}
		
		public System.Data.Linq.Table<PHUXE> PHUXEs
		{
			get
			{
				return this.GetTable<PHUXE>();
			}
		}
		
		public System.Data.Linq.Table<TAIXE> TAIXEs
		{
			get
			{
				return this.GetTable<TAIXE>();
			}
		}
		
		public System.Data.Linq.Table<TUYENDI> TUYENDIs
		{
			get
			{
				return this.GetTable<TUYENDI>();
			}
		}
		
		public System.Data.Linq.Table<VE> VEs
		{
			get
			{
				return this.GetTable<VE>();
			}
		}
		
		public System.Data.Linq.Table<XE> XEs
		{
			get
			{
				return this.GetTable<XE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYENDI")]
	public partial class CHUYENDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_TUYENDI;
		
		private System.Nullable<int> _ID_XE;
		
		private System.Nullable<int> _ID_TAIXE1;
		
		private System.Nullable<int> _ID_TAIXE2;
		
		private System.Nullable<int> _ID_PHUXE;
		
		private System.Nullable<System.DateTime> _NGAYKHOIHANH;
		
		private System.Nullable<System.TimeSpan> _GIODI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_TUYENDIChanging(System.Nullable<int> value);
    partial void OnID_TUYENDIChanged();
    partial void OnID_XEChanging(System.Nullable<int> value);
    partial void OnID_XEChanged();
    partial void OnID_TAIXE1Changing(System.Nullable<int> value);
    partial void OnID_TAIXE1Changed();
    partial void OnID_TAIXE2Changing(System.Nullable<int> value);
    partial void OnID_TAIXE2Changed();
    partial void OnID_PHUXEChanging(System.Nullable<int> value);
    partial void OnID_PHUXEChanged();
    partial void OnNGAYKHOIHANHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKHOIHANHChanged();
    partial void OnGIODIChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGIODIChanged();
    #endregion
		
		public CHUYENDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYENDI", DbType="Int")]
		public System.Nullable<int> ID_TUYENDI
		{
			get
			{
				return this._ID_TUYENDI;
			}
			set
			{
				if ((this._ID_TUYENDI != value))
				{
					this.OnID_TUYENDIChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYENDI = value;
					this.SendPropertyChanged("ID_TUYENDI");
					this.OnID_TUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", DbType="Int")]
		public System.Nullable<int> ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					this.OnID_XEChanging(value);
					this.SendPropertyChanging();
					this._ID_XE = value;
					this.SendPropertyChanged("ID_XE");
					this.OnID_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TAIXE1", DbType="Int")]
		public System.Nullable<int> ID_TAIXE1
		{
			get
			{
				return this._ID_TAIXE1;
			}
			set
			{
				if ((this._ID_TAIXE1 != value))
				{
					this.OnID_TAIXE1Changing(value);
					this.SendPropertyChanging();
					this._ID_TAIXE1 = value;
					this.SendPropertyChanged("ID_TAIXE1");
					this.OnID_TAIXE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TAIXE2", DbType="Int")]
		public System.Nullable<int> ID_TAIXE2
		{
			get
			{
				return this._ID_TAIXE2;
			}
			set
			{
				if ((this._ID_TAIXE2 != value))
				{
					this.OnID_TAIXE2Changing(value);
					this.SendPropertyChanging();
					this._ID_TAIXE2 = value;
					this.SendPropertyChanged("ID_TAIXE2");
					this.OnID_TAIXE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHUXE", DbType="Int")]
		public System.Nullable<int> ID_PHUXE
		{
			get
			{
				return this._ID_PHUXE;
			}
			set
			{
				if ((this._ID_PHUXE != value))
				{
					this.OnID_PHUXEChanging(value);
					this.SendPropertyChanging();
					this._ID_PHUXE = value;
					this.SendPropertyChanged("ID_PHUXE");
					this.OnID_PHUXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKHOIHANH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYKHOIHANH
		{
			get
			{
				return this._NGAYKHOIHANH;
			}
			set
			{
				if ((this._NGAYKHOIHANH != value))
				{
					this.OnNGAYKHOIHANHChanging(value);
					this.SendPropertyChanging();
					this._NGAYKHOIHANH = value;
					this.SendPropertyChanged("NGAYKHOIHANH");
					this.OnNGAYKHOIHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIODI", DbType="Time")]
		public System.Nullable<System.TimeSpan> GIODI
		{
			get
			{
				return this._GIODI;
			}
			set
			{
				if ((this._GIODI != value))
				{
					this.OnGIODIChanging(value);
					this.SendPropertyChanging();
					this._GIODI = value;
					this.SendPropertyChanged("GIODI");
					this.OnGIODIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIADIEMLENXE")]
	public partial class DIADIEMLENXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_TUYENDI;
		
		private string _TENDD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_TUYENDIChanging(System.Nullable<int> value);
    partial void OnID_TUYENDIChanged();
    partial void OnTENDDChanging(string value);
    partial void OnTENDDChanged();
    #endregion
		
		public DIADIEMLENXE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYENDI", DbType="Int")]
		public System.Nullable<int> ID_TUYENDI
		{
			get
			{
				return this._ID_TUYENDI;
			}
			set
			{
				if ((this._ID_TUYENDI != value))
				{
					this.OnID_TUYENDIChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYENDI = value;
					this.SendPropertyChanged("ID_TUYENDI");
					this.OnID_TUYENDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDD", DbType="NVarChar(350)")]
		public string TENDD
		{
			get
			{
				return this._TENDD;
			}
			set
			{
				if ((this._TENDD != value))
				{
					this.OnTENDDChanging(value);
					this.SendPropertyChanging();
					this._TENDD = value;
					this.SendPropertyChanged("TENDD");
					this.OnTENDDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GHE")]
	public partial class GHE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_LOAIXE;
		
		private string _TENGHE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_LOAIXEChanging(System.Nullable<int> value);
    partial void OnID_LOAIXEChanged();
    partial void OnTENGHEChanging(string value);
    partial void OnTENGHEChanged();
    #endregion
		
		public GHE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIXE", DbType="Int")]
		public System.Nullable<int> ID_LOAIXE
		{
			get
			{
				return this._ID_LOAIXE;
			}
			set
			{
				if ((this._ID_LOAIXE != value))
				{
					this.OnID_LOAIXEChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIXE = value;
					this.SendPropertyChanged("ID_LOAIXE");
					this.OnID_LOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGHE", DbType="NVarChar(50)")]
		public string TENGHE
		{
			get
			{
				return this._TENGHE;
			}
			set
			{
				if ((this._TENGHE != value))
				{
					this.OnTENGHEChanging(value);
					this.SendPropertyChanging();
					this._TENGHE = value;
					this.SendPropertyChanged("TENGHE");
					this.OnTENGHEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HOTENKH;
		
		private string _SDT;
		
		private string _EMAIL;
		
		private string _PASSWORD;
		
		private string _DIACHI;
		
		private System.Nullable<int> _ID_LoaiNguoiDung;
		
		private string _CMND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHOTENKHChanging(string value);
    partial void OnHOTENKHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnID_LoaiNguoiDungChanging(System.Nullable<int> value);
    partial void OnID_LoaiNguoiDungChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    #endregion
		
		public KHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENKH", DbType="NVarChar(50)")]
		public string HOTENKH
		{
			get
			{
				return this._HOTENKH;
			}
			set
			{
				if ((this._HOTENKH != value))
				{
					this.OnHOTENKHChanging(value);
					this.SendPropertyChanging();
					this._HOTENKH = value;
					this.SendPropertyChanged("HOTENKH");
					this.OnHOTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(250)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LoaiNguoiDung", DbType="Int")]
		public System.Nullable<int> ID_LoaiNguoiDung
		{
			get
			{
				return this._ID_LoaiNguoiDung;
			}
			set
			{
				if ((this._ID_LoaiNguoiDung != value))
				{
					this.OnID_LoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._ID_LoaiNguoiDung = value;
					this.SendPropertyChanged("ID_LoaiNguoiDung");
					this.OnID_LoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(11)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LIENHE")]
	public partial class LIENHE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HOTEN;
		
		private string _NOIDUNG;
		
		private string _SDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public LIENHE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(250)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(1000)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAINGUOIDUNG")]
	public partial class LOAINGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoaiNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiNguoiDungChanging(string value);
    partial void OnTenLoaiNguoiDungChanged();
    #endregion
		
		public LOAINGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiNguoiDung", DbType="NVarChar(100)")]
		public string TenLoaiNguoiDung
		{
			get
			{
				return this._TenLoaiNguoiDung;
			}
			set
			{
				if ((this._TenLoaiNguoiDung != value))
				{
					this.OnTenLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiNguoiDung = value;
					this.SendPropertyChanged("TenLoaiNguoiDung");
					this.OnTenLoaiNguoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAINHANVIEN")]
	public partial class LOAINHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TENLOAINV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTENLOAINVChanging(string value);
    partial void OnTENLOAINVChanged();
    #endregion
		
		public LOAINHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAINV", DbType="NVarChar(50)")]
		public string TENLOAINV
		{
			get
			{
				return this._TENLOAINV;
			}
			set
			{
				if ((this._TENLOAINV != value))
				{
					this.OnTENLOAINVChanging(value);
					this.SendPropertyChanging();
					this._TENLOAINV = value;
					this.SendPropertyChanged("TENLOAINV");
					this.OnTENLOAINVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIXE")]
	public partial class LOAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _TENLOAIXE;
		
		private System.Nullable<int> _SOCHONGOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnTENLOAIXEChanging(string value);
    partial void OnTENLOAIXEChanged();
    partial void OnSOCHONGOIChanging(System.Nullable<int> value);
    partial void OnSOCHONGOIChanged();
    #endregion
		
		public LOAIXE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIXE", DbType="NVarChar(50)")]
		public string TENLOAIXE
		{
			get
			{
				return this._TENLOAIXE;
			}
			set
			{
				if ((this._TENLOAIXE != value))
				{
					this.OnTENLOAIXEChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIXE = value;
					this.SendPropertyChanged("TENLOAIXE");
					this.OnTENLOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCHONGOI", DbType="Int")]
		public System.Nullable<int> SOCHONGOI
		{
			get
			{
				return this._SOCHONGOI;
			}
			set
			{
				if ((this._SOCHONGOI != value))
				{
					this.OnSOCHONGOIChanging(value);
					this.SendPropertyChanging();
					this._SOCHONGOI = value;
					this.SendPropertyChanged("SOCHONGOI");
					this.OnSOCHONGOIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_LOAINV;
		
		private string _HOTENNV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_LOAINVChanging(System.Nullable<int> value);
    partial void OnID_LOAINVChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public NHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAINV", DbType="Int")]
		public System.Nullable<int> ID_LOAINV
		{
			get
			{
				return this._ID_LOAINV;
			}
			set
			{
				if ((this._ID_LOAINV != value))
				{
					this.OnID_LOAINVChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAINV = value;
					this.SendPropertyChanged("ID_LOAINV");
					this.OnID_LOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="NVarChar(50)")]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(250)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDEN")]
	public partial class NOIDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TENNOIDEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTENNOIDENChanging(string value);
    partial void OnTENNOIDENChanged();
    #endregion
		
		public NOIDEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNOIDEN", DbType="NVarChar(50)")]
		public string TENNOIDEN
		{
			get
			{
				return this._TENNOIDEN;
			}
			set
			{
				if ((this._TENNOIDEN != value))
				{
					this.OnTENNOIDENChanging(value);
					this.SendPropertyChanging();
					this._TENNOIDEN = value;
					this.SendPropertyChanged("TENNOIDEN");
					this.OnTENNOIDENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDI")]
	public partial class NOIDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TENNOIDI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTENNOIDIChanging(string value);
    partial void OnTENNOIDIChanged();
    #endregion
		
		public NOIDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNOIDI", DbType="NVarChar(50)")]
		public string TENNOIDI
		{
			get
			{
				return this._TENNOIDI;
			}
			set
			{
				if ((this._TENNOIDI != value))
				{
					this.OnTENNOIDIChanging(value);
					this.SendPropertyChanging();
					this._TENNOIDI = value;
					this.SendPropertyChanged("TENNOIDI");
					this.OnTENNOIDIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUXE")]
	public partial class PHUXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_LOAINV;
		
		private string _HOTENPX;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_LOAINVChanging(System.Nullable<int> value);
    partial void OnID_LOAINVChanged();
    partial void OnHOTENPXChanging(string value);
    partial void OnHOTENPXChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public PHUXE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAINV", DbType="Int")]
		public System.Nullable<int> ID_LOAINV
		{
			get
			{
				return this._ID_LOAINV;
			}
			set
			{
				if ((this._ID_LOAINV != value))
				{
					this.OnID_LOAINVChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAINV = value;
					this.SendPropertyChanged("ID_LOAINV");
					this.OnID_LOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENPX", DbType="NVarChar(50)")]
		public string HOTENPX
		{
			get
			{
				return this._HOTENPX;
			}
			set
			{
				if ((this._HOTENPX != value))
				{
					this.OnHOTENPXChanging(value);
					this.SendPropertyChanging();
					this._HOTENPX = value;
					this.SendPropertyChanged("HOTENPX");
					this.OnHOTENPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(250)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIXE")]
	public partial class TAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_LOAINV;
		
		private string _HOTENTX;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_LOAINVChanging(System.Nullable<int> value);
    partial void OnID_LOAINVChanged();
    partial void OnHOTENTXChanging(string value);
    partial void OnHOTENTXChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public TAIXE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAINV", DbType="Int")]
		public System.Nullable<int> ID_LOAINV
		{
			get
			{
				return this._ID_LOAINV;
			}
			set
			{
				if ((this._ID_LOAINV != value))
				{
					this.OnID_LOAINVChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAINV = value;
					this.SendPropertyChanged("ID_LOAINV");
					this.OnID_LOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENTX", DbType="NVarChar(50)")]
		public string HOTENTX
		{
			get
			{
				return this._HOTENTX;
			}
			set
			{
				if ((this._HOTENTX != value))
				{
					this.OnHOTENTXChanging(value);
					this.SendPropertyChanging();
					this._HOTENTX = value;
					this.SendPropertyChanged("HOTENTX");
					this.OnHOTENTXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(250)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUYENDI")]
	public partial class TUYENDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_NOIDI;
		
		private System.Nullable<int> _ID_NOIDEN;
		
		private System.Nullable<int> _ID_LOAIXE;
		
		private string _TENTUYEN;
		
		private System.Nullable<double> _DONGIA;
		
		private System.Nullable<double> _KHOANGCACH;
		
		private System.Nullable<double> _SOGIOCHAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_NOIDIChanging(System.Nullable<int> value);
    partial void OnID_NOIDIChanged();
    partial void OnID_NOIDENChanging(System.Nullable<int> value);
    partial void OnID_NOIDENChanged();
    partial void OnID_LOAIXEChanging(System.Nullable<int> value);
    partial void OnID_LOAIXEChanged();
    partial void OnTENTUYENChanging(string value);
    partial void OnTENTUYENChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    partial void OnKHOANGCACHChanging(System.Nullable<double> value);
    partial void OnKHOANGCACHChanged();
    partial void OnSOGIOCHAYChanging(System.Nullable<double> value);
    partial void OnSOGIOCHAYChanged();
    #endregion
		
		public TUYENDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NOIDI", DbType="Int")]
		public System.Nullable<int> ID_NOIDI
		{
			get
			{
				return this._ID_NOIDI;
			}
			set
			{
				if ((this._ID_NOIDI != value))
				{
					this.OnID_NOIDIChanging(value);
					this.SendPropertyChanging();
					this._ID_NOIDI = value;
					this.SendPropertyChanged("ID_NOIDI");
					this.OnID_NOIDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NOIDEN", DbType="Int")]
		public System.Nullable<int> ID_NOIDEN
		{
			get
			{
				return this._ID_NOIDEN;
			}
			set
			{
				if ((this._ID_NOIDEN != value))
				{
					this.OnID_NOIDENChanging(value);
					this.SendPropertyChanging();
					this._ID_NOIDEN = value;
					this.SendPropertyChanged("ID_NOIDEN");
					this.OnID_NOIDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIXE", DbType="Int")]
		public System.Nullable<int> ID_LOAIXE
		{
			get
			{
				return this._ID_LOAIXE;
			}
			set
			{
				if ((this._ID_LOAIXE != value))
				{
					this.OnID_LOAIXEChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIXE = value;
					this.SendPropertyChanged("ID_LOAIXE");
					this.OnID_LOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTUYEN", DbType="NVarChar(150)")]
		public string TENTUYEN
		{
			get
			{
				return this._TENTUYEN;
			}
			set
			{
				if ((this._TENTUYEN != value))
				{
					this.OnTENTUYENChanging(value);
					this.SendPropertyChanging();
					this._TENTUYEN = value;
					this.SendPropertyChanged("TENTUYEN");
					this.OnTENTUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOANGCACH", DbType="Float")]
		public System.Nullable<double> KHOANGCACH
		{
			get
			{
				return this._KHOANGCACH;
			}
			set
			{
				if ((this._KHOANGCACH != value))
				{
					this.OnKHOANGCACHChanging(value);
					this.SendPropertyChanging();
					this._KHOANGCACH = value;
					this.SendPropertyChanged("KHOANGCACH");
					this.OnKHOANGCACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOGIOCHAY", DbType="Float")]
		public System.Nullable<double> SOGIOCHAY
		{
			get
			{
				return this._SOGIOCHAY;
			}
			set
			{
				if ((this._SOGIOCHAY != value))
				{
					this.OnSOGIOCHAYChanging(value);
					this.SendPropertyChanging();
					this._SOGIOCHAY = value;
					this.SendPropertyChanged("SOGIOCHAY");
					this.OnSOGIOCHAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VE")]
	public partial class VE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _NGAYDAT;
		
		private System.Nullable<double> _TONGTIEN;
		
		private System.Nullable<int> _ID_CHUYEN;
		
		private System.Nullable<int> _ID_DIADIEMLX;
		
		private string _ID_GHE;
		
		private string _HOTEN;
		
		private string _EMAIL;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private System.Nullable<int> _ID_KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNGAYDATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDATChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    partial void OnID_CHUYENChanging(System.Nullable<int> value);
    partial void OnID_CHUYENChanged();
    partial void OnID_DIADIEMLXChanging(System.Nullable<int> value);
    partial void OnID_DIADIEMLXChanged();
    partial void OnID_GHEChanging(string value);
    partial void OnID_GHEChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnID_KHACHHANGChanging(System.Nullable<int> value);
    partial void OnID_KHACHHANGChanged();
    #endregion
		
		public VE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDAT
		{
			get
			{
				return this._NGAYDAT;
			}
			set
			{
				if ((this._NGAYDAT != value))
				{
					this.OnNGAYDATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDAT = value;
					this.SendPropertyChanged("NGAYDAT");
					this.OnNGAYDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CHUYEN", DbType="Int")]
		public System.Nullable<int> ID_CHUYEN
		{
			get
			{
				return this._ID_CHUYEN;
			}
			set
			{
				if ((this._ID_CHUYEN != value))
				{
					this.OnID_CHUYENChanging(value);
					this.SendPropertyChanging();
					this._ID_CHUYEN = value;
					this.SendPropertyChanged("ID_CHUYEN");
					this.OnID_CHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIADIEMLX", DbType="Int")]
		public System.Nullable<int> ID_DIADIEMLX
		{
			get
			{
				return this._ID_DIADIEMLX;
			}
			set
			{
				if ((this._ID_DIADIEMLX != value))
				{
					this.OnID_DIADIEMLXChanging(value);
					this.SendPropertyChanging();
					this._ID_DIADIEMLX = value;
					this.SendPropertyChanged("ID_DIADIEMLX");
					this.OnID_DIADIEMLXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GHE", DbType="NVarChar(50)")]
		public string ID_GHE
		{
			get
			{
				return this._ID_GHE;
			}
			set
			{
				if ((this._ID_GHE != value))
				{
					this.OnID_GHEChanging(value);
					this.SendPropertyChanging();
					this._ID_GHE = value;
					this.SendPropertyChanged("ID_GHE");
					this.OnID_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACHHANG", DbType="Int")]
		public System.Nullable<int> ID_KHACHHANG
		{
			get
			{
				return this._ID_KHACHHANG;
			}
			set
			{
				if ((this._ID_KHACHHANG != value))
				{
					this.OnID_KHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACHHANG = value;
					this.SendPropertyChanged("ID_KHACHHANG");
					this.OnID_KHACHHANGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XE")]
	public partial class XE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_LOAIXE;
		
		private string _BIENSO;
		
		private string _TRANGTHAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_LOAIXEChanging(System.Nullable<int> value);
    partial void OnID_LOAIXEChanged();
    partial void OnBIENSOChanging(string value);
    partial void OnBIENSOChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public XE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIXE", DbType="Int")]
		public System.Nullable<int> ID_LOAIXE
		{
			get
			{
				return this._ID_LOAIXE;
			}
			set
			{
				if ((this._ID_LOAIXE != value))
				{
					this.OnID_LOAIXEChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIXE = value;
					this.SendPropertyChanged("ID_LOAIXE");
					this.OnID_LOAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIENSO", DbType="VarChar(50)")]
		public string BIENSO
		{
			get
			{
				return this._BIENSO;
			}
			set
			{
				if ((this._BIENSO != value))
				{
					this.OnBIENSOChanging(value);
					this.SendPropertyChanging();
					this._BIENSO = value;
					this.SendPropertyChanged("BIENSO");
					this.OnBIENSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
